[package]
name = "pacont"
version = "0.5.2"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
walkdir = "2"
arboard = { version = "3.4", default-features = false }

[dev-dependencies]
tempfile = "3"
